#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM artifactorycloud.ual.com/l-docker/datadog/dotnet/runtime:3.1-1.28.7 AS base
WORKDIR /app
EXPOSE 80

FROM artifactorycloud.ual.com/l-docker/ms/dotnet/core/sdk:3.1 AS build
WORKDIR /

COPY ["src/Services/ReShopping/EligibleCheck/United.Mobile.EligibleCheck.Api/United.Mobile.EligibleCheck.Api.csproj", "src/Services/ReShopping/EligibleCheck/United.Mobile.EligibleCheck.Api/"]
COPY ["src/Services/ReShopping/EligibleCheck/United.Mobile.EligibleCheck.Domain/United.Mobile.EligibleCheck.Domain.csproj", "src/Services/ReShopping/EligibleCheck/United.Mobile.EligibleCheck.Domain/"]
COPY ["src/DataAccess/United.Mobile.DataAccess.Common/United.Mobile.DataAccess.Common.csproj", "src/DataAccess/United.Mobile.DataAccess.Common/"]
COPY ["src/Core/United.Utility/United.Utility.csproj", "src/Core/United.Utility/"]
COPY ["src/Core/United.Ebs.Logging/United.Ebs.Logging.csproj", "src/Core/United.Ebs.Logging/"]
COPY ["src/Model/United.Mobile.Model.Common/United.Mobile.Model.Common.csproj", "src/Model/United.Mobile.Model.Common/"]
COPY ["src/Model/SeatEngine/United.Mobile.Model.SeatEngine/United.Mobile.Model.SeatEngine.csproj", "src/Model/SeatEngine/United.Mobile.Model.SeatEngine/"]
COPY ["src/Model.Internal/United.Mobile.Model.Internal.Exception/United.Mobile.Model.Internal.Exception.csproj", "src/Model.Internal/United.Mobile.Model.Internal.Exception/"]
COPY ["src/Model.Internal/United.Definition/United.Mobile.Model.Internal.Common.csproj", "src/Model.Internal/United.Definition/"]
COPY ["src/Model.Internal/United.Mobile.Model.Internal/United.Mobile.Model.Internal.csproj", "src/Model.Internal/United.Mobile.Model.Internal/"]
COPY ["src/Model/eRes/United.Mobile.Model.HomePageContent/United.Mobile.Model.HomePageContent.csproj", "src/Model/eRes/United.Mobile.Model.HomePageContent/"]
COPY ["src/Model/ReShopping/United.Mobile.Model.ReShop/United.Mobile.Model.ReShop.csproj", "src/Model/ReShopping/United.Mobile.Model.ReShop/"]
COPY ["src/Model/Shopping/United.Mobile.Model.Common/United.Mobile.Model.Shopping.Common.csproj", "src/Model/Shopping/United.Mobile.Model.Common/"]
COPY ["src/Model/Ancillary/United.Mobile.Model.Catalog/United.Mobile.Model.Catalog.csproj", "src/Model/Ancillary/United.Mobile.Model.Catalog/"]
COPY ["src/Model/PNRManagement/United.Mobile.Model.PNRManagement/United.Mobile.Model.PNRManagement.csproj", "src/Model/PNRManagement/United.Mobile.Model.PNRManagement/"]
COPY ["src/Model/AccountManagement/United.Mobile.Model.AccountManagement/United.Mobile.Model.MPSignIn.csproj", "src/Model/AccountManagement/United.Mobile.Model.AccountManagement/"]
COPY ["src/Model/Shopping/United.Mobile.Model.Booking/United.Mobile.Model.Booking.csproj", "src/Model/Shopping/United.Mobile.Model.Booking/"]
COPY ["src/Model/MSCPayment/United.Mobile.Model.TravelCredit/United.Mobile.Model.TravelCredit.csproj", "src/Model/MSCPayment/United.Mobile.Model.TravelCredit/"]
COPY ["src/Model/MSCPayment/Enum/United.Mobile.MSCPayment.Enum/United.Mobile.MSCPayment.Enum.csproj", "src/Model/MSCPayment/Enum/United.Mobile.MSCPayment.Enum/"]
COPY ["src/Model/Payment/United.Mobile.Model.Payment/United.Mobile.Model.Payment.csproj", "src/Model/Payment/United.Mobile.Model.Payment/"]
COPY ["src/Model/Shopping/United.Mobile.Model.Shopping/United.Mobile.Model.Shopping.csproj", "src/Model/Shopping/United.Mobile.Model.Shopping/"]
COPY ["src/Model/Shopping/United.Mobile.Model.ShopAward/United.Mobile.Model.ShopAward.csproj", "src/Model/Shopping/United.Mobile.Model.ShopAward/"]
COPY ["src/Model/FlightStatus/United.Mobile.Model.FlightStatus/United.Mobile.Model.FlightStatus.csproj", "src/Model/FlightStatus/United.Mobile.Model.FlightStatus/"]
COPY ["src/Model/AccountManagement/United.Mobile.Model.UpdateMemberProfile/United.Mobile.Model.UpdateMemberProfile.csproj", "src/Model/AccountManagement/United.Mobile.Model.UpdateMemberProfile/"]
COPY ["src/Model/AccountManagement/United.Mobile.Model.MemberProfile/United.Mobile.Model.MemberProfile.csproj", "src/Model/AccountManagement/United.Mobile.Model.MemberProfile/"]
COPY ["src/Model/Shopping/United.Mobile.Model.EmpShop/United.Mobile.Model.EmpShop.csproj", "src/Model/Shopping/United.Mobile.Model.EmpShop/"]
COPY ["src/Model/ManageRes/United.Mobile.Model.ManageRes/United.Mobile.Model.ManageRes.csproj", "src/Model/ManageRes/United.Mobile.Model.ManageRes/"]
COPY ["src/DataAccess/Ancillary/United.Mobile.DataAccess.Fitbit/United.Mobile.DataAccess.Fitbit.csproj", "src/DataAccess/Ancillary/United.Mobile.DataAccess.Fitbit/"]
COPY ["src/Model/Ancillary/United.Mobile.Model.Fitbit/United.Mobile.Model.Fitbit.csproj", "src/Model/Ancillary/United.Mobile.Model.Fitbit/"]
COPY ["src/Model/Ancillary/United.Mobile.Model.FeedBack/United.Mobile.Model.FeedBack.csproj", "src/Model/Ancillary/United.Mobile.Model.FeedBack/"]
COPY ["src/Model/AccountManagement/United.Mobile.Model.MPRewards/United.Mobile.Model.MPRewards.csproj", "src/Model/AccountManagement/United.Mobile.Model.MPRewards/"]
COPY ["src/Services/ReShopping/ReShop/United.Mobile.ReShop.Domain/United.Mobile.ReShop.Domain.csproj", "src/Services/ReShopping/ReShop/United.Mobile.ReShop.Domain/"]
COPY ["src/Core/Common/United.Common.Helper.PageProduct/United.Common.Helper.PageProduct.csproj", "src/Core/Common/United.Common.Helper.PageProduct/"]
COPY ["src/Core/Common/United.Common.Helper.Profile/United.Common.Helper.Profile.csproj", "src/Core/Common/United.Common.Helper.Profile/"]
COPY ["src/DataAccess/AccountManagement/United.Mobile.DataAccess.Profile/United.Mobile.DataAccess.Profile.csproj", "src/DataAccess/AccountManagement/United.Mobile.DataAccess.Profile/"]
COPY ["src/DataAccess/AccountManagement/United.Mobile.DataAccess.Loyalty/United.Mobile.DataAccess.Loyalty.csproj", "src/DataAccess/AccountManagement/United.Mobile.DataAccess.Loyalty/"]
COPY ["src/Model/UnitedClubPasses/United.Mobile.Model.UnitedClubPasses/United.Mobile.Model.UnitedClubPasses.csproj", "src/Model/UnitedClubPasses/United.Mobile.Model.UnitedClubPasses/"]
COPY ["src/DataAccess/AccountManagement/United.Mobile.DataAccess.MPAuthentication/United.Mobile.DataAccess.MPAuthentication.csproj", "src/DataAccess/AccountManagement/United.Mobile.DataAccess.MPAuthentication/"]
COPY ["src/DataAccess/AccountManagement/United.Mobile.DataAccess.MemberSignIn/United.Mobile.DataAccess.MemberSignIn.csproj", "src/DataAccess/AccountManagement/United.Mobile.DataAccess.MemberSignIn/"]
COPY ["src/Model.Internal/AccountManagement/United.Mobile.Model.Internal.AccountManagement/United.Mobile.Model.Internal.AccountManagement.csproj", "src/Model.Internal/AccountManagement/United.Mobile.Model.Internal.AccountManagement/"]
COPY ["src/DataAccess/UnitedClubPasses/United.Mobile.DataAccess.UnitedClub/United.Mobile.DataAccess.UnitedClub.csproj", "src/DataAccess/UnitedClubPasses/United.Mobile.DataAccess.UnitedClub/"]
COPY ["src/Core/United.Common.Helper/United.Common.Helper.csproj", "src/Core/United.Common.Helper/"]
COPY ["src/DataAccess/OnPrem/United.Mobile.DataAccess.OnPremiseSQLSP/United.Mobile.DataAccess.OnPremiseSQLSP.csproj", "src/DataAccess/OnPrem/United.Mobile.DataAccess.OnPremiseSQLSP/"]
COPY ["src/Model/BagCalculator/United.Mobile.Model.BagCalculator/United.Mobile.Model.BagCalculator.csproj", "src/Model/BagCalculator/United.Mobile.Model.BagCalculator/"]
COPY ["src/Model/AccountManagement/United.Mobile.Model.DeviceInitialization/United.Mobile.Model.DeviceInitialization.csproj", "src/Model/AccountManagement/United.Mobile.Model.DeviceInitialization/"]
COPY ["src/DataAccess/United.Mobile.DataAccess.DynamoDB/United.Mobile.DataAccess.DynamoDB.csproj", "src/DataAccess/United.Mobile.DataAccess.DynamoDB/"]
COPY ["src/Model/ClubPasses/United.Mobile.Model.ClubPasses/United.Mobile.Model.ClubPasses.csproj", "src/Model/ClubPasses/United.Mobile.Model.ClubPasses/"]
COPY ["src/DataAccess/Shopping/United.Mobile.DataAccess.ShopTrips/United.Mobile.DataAccess.ShopTrips.csproj", "src/DataAccess/Shopping/United.Mobile.DataAccess.ShopTrips/"]
COPY ["src/DataAccess/BagCalculator/United.Mobile.DataAccess.CMSContent/United.Mobile.DataAccess.CMSContent.csproj", "src/DataAccess/BagCalculator/United.Mobile.DataAccess.CMSContent/"]
COPY ["src/DataAccess/ManageReservation/United.Mobile.DataAccess.ManageReservation/United.Mobile.DataAccess.ManageReservation.csproj", "src/DataAccess/ManageReservation/United.Mobile.DataAccess.ManageReservation/"]
COPY ["src/DataAccess/AccountManagement/United.Mobile.DataAccess.ETC/United.Mobile.DataAccess.ETC.csproj", "src/DataAccess/AccountManagement/United.Mobile.DataAccess.ETC/"]
COPY ["src/Core/Common/United.Common.Helper.FlightStatus/United.Common.Helper.FlightStatus.csproj", "src/Core/Common/United.Common.Helper.FlightStatus/"]
COPY ["src/DataAccess/FlightStatus/United.Mobile.DataAccess.FlightStatus/United.Mobile.DataAccess.FlightStatus.csproj", "src/DataAccess/FlightStatus/United.Mobile.DataAccess.FlightStatus/"]
COPY ["src/Core/Common/United.Common.Helper.EmployeeReservation/United.Common.Helper.EmployeeReservation.csproj", "src/Core/Common/United.Common.Helper.EmployeeReservation/"]
COPY ["src/DataAccess/AccountManagement/United.Mobile.DataAccess.Customer/United.Mobile.DataAccess.Customer.csproj", "src/DataAccess/AccountManagement/United.Mobile.DataAccess.Customer/"]
COPY ["src/DataAccess/AccountManagement/United.Mobile.DataAccess.MPRewards/United.Mobile.DataAccess.MPRewards.csproj", "src/DataAccess/AccountManagement/United.Mobile.DataAccess.MPRewards/"]
COPY ["src/Core/Common/United.Common.Helper.FSRHandler/United.Common.Helper.FSRHandler.csproj", "src/Core/Common/United.Common.Helper.FSRHandler/"]
COPY ["src/Core/Common/United.Common.Helper.Shopping/United.Common.Helper.Shopping.csproj", "src/Core/Common/United.Common.Helper.Shopping/"]
COPY ["src/Model/Shopping/United.Mobile.Model.ShopTrips/United.Mobile.Model.ShopTrips.csproj", "src/Model/Shopping/United.Mobile.Model.ShopTrips/"]
COPY ["src/DataAccess/United.Mobile.DataAccess.MerchandizeService/United.Mobile.DataAccess.MerchandizeService.csproj", "src/DataAccess/United.Mobile.DataAccess.MerchandizeService/"]
COPY ["src/DataAccess/United.Mobile.DataAccess.FlightShopping/United.Mobile.DataAccess.FlightShopping.csproj", "src/DataAccess/United.Mobile.DataAccess.FlightShopping/"]
COPY ["src/DataAccess/ReShopping/United.Mobile.DataAccess.EligibleCheck/United.Mobile.DataAccess.EligibleCheck.csproj", "src/DataAccess/ReShopping/United.Mobile.DataAccess.EligibleCheck/"]
COPY ["src/Core/Common/United.Common.Helper.ManageRes/United.Common.Helper.ManageRes.csproj", "src/Core/Common/United.Common.Helper.ManageRes/"]
COPY ["src/Core/Common/United.Common.Helper.SeatEngine/United.Common.Helper.SeatEngine.csproj", "src/Core/Common/United.Common.Helper.SeatEngine/"]
COPY ["src/Core/Common/United.Common.Helper.Merchandize/United.Common.Helper.Merchandize.csproj", "src/Core/Common/United.Common.Helper.Merchandize/"]
COPY ["src/DataAccess/Shopping/United.Mobile.DataAccess.ShopProducts/United.Mobile.DataAccess.ShopProducts.csproj", "src/DataAccess/Shopping/United.Mobile.DataAccess.ShopProducts/"]
COPY ["src/Model/MSCPayment/United.Mobile.Model.MSCRegister/United.Mobile.Model.MSCRegister.csproj", "src/Model/MSCPayment/United.Mobile.Model.MSCRegister/"]
COPY ["src/Model/MSCPayment/United.Mobile.Model.MSCCheckOut/United.Mobile.Model.MSCCheckOut.csproj", "src/Model/MSCPayment/United.Mobile.Model.MSCCheckOut/"]
COPY ["src/Model/SeatMap/United.Mobile.Model.SeatMap/United.Mobile.Model.SeatMap.csproj", "src/Model/SeatMap/United.Mobile.Model.SeatMap/"]
COPY ["src/Model/Shopping/United.Mobile.Model.ShopSeats/United.Mobile.Model.ShopSeats.csproj", "src/Model/Shopping/United.Mobile.Model.ShopSeats/"]
COPY ["src/DataAccess/Shopping/United.Mobile.DataAccess.ShopSeats/United.Mobile.DataAccess.ShopSeats.csproj", "src/DataAccess/Shopping/United.Mobile.DataAccess.ShopSeats/"]
COPY ["src/DataAccess/SeatEngine/United.Mobile.DataAccess.SeatEngine/United.Mobile.DataAccess.SeatEngine.csproj", "src/DataAccess/SeatEngine/United.Mobile.DataAccess.SeatEngine/"]
COPY ["src/Model/ManageRes/United.Mobile.Model.FlightReservation/United.Mobile.Model.FlightReservation.csproj", "src/Model/ManageRes/United.Mobile.Model.FlightReservation/"]
COPY ["src/DataAccess/ManageReservation/United.Mobile.DataAccess.FlightReservation/United.Mobile.DataAccess.FlightReservation.csproj", "src/DataAccess/ManageReservation/United.Mobile.DataAccess.FlightReservation/"]

ARG Username
ARG PAT
RUN echo '<?xml version="1.0" encoding="utf-8"?> \
<configuration> \
  <packageSources> \
    <clear /> \
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" /> \
    <add key="ArtifactoryNuGetV3" value="https://artifactory.ual.com/artifactory/api/nuget/v3/nuget" protocolVersion="3" /> \
  </packageSources> \
  <activePackageSource> \
    <add key="All" value="(Aggregate source)" /> \
  </activePackageSource> \
</configuration>' > nuget.config && \
if [ -n "$Username" ] && [ -n "$PAT" ]; then \
sed -i "s|</configuration>|<packageSourceCredentials><Products><add key=\"Username\" value=\"PAT\" /><add key=\"ClearTextPassword\" value=\"${PAT}\" /></Products></packageSourceCredentials></configuration>|" nuget.config; \
fi && \
cat ./nuget.config

COPY . .
WORKDIR "/src/Services/ReShopping/EligibleCheck/United.Mobile.EligibleCheck.Api"

FROM build AS publish
RUN dotnet publish "United.Mobile.EligibleCheck.Api.csproj" -c Release --self-contained -r linux-x64 -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "United.Mobile.EligibleCheck.Api.dll"]