//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAWSPNRServiceERes
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Webservices.Continental.Com/COWSPNR", ConfigurationName="UAWSPNRServiceERes.PNRServiceSoap")]
    public interface PNRServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Webservices.Continental.Com/COWSPNR/HeartBeat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> HeartBeatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Webservices.Continental.Com/COWSPNR/GetPNRRecordsByEmployeeID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordsByEmployeeIDAsync(string employeeID, string activePNROnly, string accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Webservices.Continental.Com/COWSPNR/GetReservationByEmployeeID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetReservationByEmployeeIDAsync(string employeeID, string activePNROnly, string accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Webservices.Continental.Com/COWSPNR/GetReservationByOnePass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetReservationByOnePassAsync(string onePass, string activePNROnly, string accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Webservices.Continental.Com/COWSPNR/GetPNRRecordsByOnePass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordsByOnePassAsync(string onePass, string activePNROnly, string accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Webservices.Continental.Com/COWSPNR/GetPNRRecordByPNR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordByPNRAsync(string recordLocator, string accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Webservices.Continental.Com/COWSPNR/GetPNRRecordByPNRForClub", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordByPNRForClubAsync(string recordLocator, string accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Webservices.Continental.Com/COWSPNR/GetPNRRecordByRecordLocator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordByRecordLocatorAsync(string recordLocator, string redeploy, string accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Webservices.Continental.Com/COWSPNR/GetPNRRecordByPNRNoItineraryValidation" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordByPNRNoItineraryValidationAsync(string recordLocator, string accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Webservices.Continental.Com/COWSPNR/GetPNRRecordByPNRWithTktDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordByPNRWithTktDetailAsync(string recordLocator, string accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Webservices.Continental.Com/COWSPNR/GetPNRRecordByRecordLocatorWithTktDeta" +
            "il", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordByRecordLocatorWithTktDetailAsync(string recordLocator, string redeploy, string accessCode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Webservices.Continental.Com/COWSPNR")]
    public partial class COWSReturnType
    {
        
        private string inputValueField;
        
        private string employeeIDField;
        
        private PNR[] pNRCollectionField;
        
        private COWSException cOWSExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InputValue
        {
            get
            {
                return this.inputValueField;
            }
            set
            {
                this.inputValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EmployeeID
        {
            get
            {
                return this.employeeIDField;
            }
            set
            {
                this.employeeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public PNR[] PNRCollection
        {
            get
            {
                return this.pNRCollectionField;
            }
            set
            {
                this.pNRCollectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public COWSException COWSException
        {
            get
            {
                return this.cOWSExceptionField;
            }
            set
            {
                this.cOWSExceptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Webservices.Continental.Com/COWSPNR")]
    public partial class PNR
    {
        
        private string recordLocatorField;
        
        private System.DateTime dateCreatedField;
        
        private bool isActiveField;
        
        private TicketType ticketTypeField;
        
        private System.DateTime travelDateField;
        
        private string originField;
        
        private string destinationField;
        
        private string employeeIDField;
        
        private string groupNameField;
        
        private short numberOfPassengersField;
        
        private bool hasCOStarInPNRField;
        
        private ItineraryType itineraryTypeField;
        
        private bool isOpenJawField;
        
        private bool hasStopOverField;
        
        private string forceConnectionField;
        
        private Passenger[] passengersField;
        
        private Segment[] segmentsField;
        
        private StopOver[] stopOversField;
        
        private EMail[] eMailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RecordLocator
        {
            get
            {
                return this.recordLocatorField;
            }
            set
            {
                this.recordLocatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime DateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TicketType TicketType
        {
            get
            {
                return this.ticketTypeField;
            }
            set
            {
                this.ticketTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime TravelDate
        {
            get
            {
                return this.travelDateField;
            }
            set
            {
                this.travelDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string EmployeeID
        {
            get
            {
                return this.employeeIDField;
            }
            set
            {
                this.employeeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string GroupName
        {
            get
            {
                return this.groupNameField;
            }
            set
            {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public short NumberOfPassengers
        {
            get
            {
                return this.numberOfPassengersField;
            }
            set
            {
                this.numberOfPassengersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool HasCOStarInPNR
        {
            get
            {
                return this.hasCOStarInPNRField;
            }
            set
            {
                this.hasCOStarInPNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public ItineraryType ItineraryType
        {
            get
            {
                return this.itineraryTypeField;
            }
            set
            {
                this.itineraryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool IsOpenJaw
        {
            get
            {
                return this.isOpenJawField;
            }
            set
            {
                this.isOpenJawField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool HasStopOver
        {
            get
            {
                return this.hasStopOverField;
            }
            set
            {
                this.hasStopOverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ForceConnection
        {
            get
            {
                return this.forceConnectionField;
            }
            set
            {
                this.forceConnectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=15)]
        public Passenger[] Passengers
        {
            get
            {
                return this.passengersField;
            }
            set
            {
                this.passengersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public Segment[] Segments
        {
            get
            {
                return this.segmentsField;
            }
            set
            {
                this.segmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        public StopOver[] StopOvers
        {
            get
            {
                return this.stopOversField;
            }
            set
            {
                this.stopOversField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        public EMail[] EMails
        {
            get
            {
                return this.eMailsField;
            }
            set
            {
                this.eMailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Webservices.Continental.Com/COWSPNR")]
    public enum TicketType
    {
        
        /// <remarks/>
        ETKT,
        
        /// <remarks/>
        PDOC,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Webservices.Continental.Com/COWSPNR")]
    public enum ItineraryType
    {
        
        /// <remarks/>
        Oneway,
        
        /// <remarks/>
        RoundTrip,
        
        /// <remarks/>
        CircleTrip,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Webservices.Continental.Com/COWSPNR")]
    public partial class Passenger
    {
        
        private short passengerIndexField;
        
        private string passengerNumberField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        private string prefixNameField;
        
        private string suffixNameField;
        
        private short numberInPartyField;
        
        private short boardYearField;
        
        private string passClassField;
        
        private string remarksField;
        
        private string freqFlyerTypeField;
        
        private string freqFlyerIDField;
        
        private string freqFlyerCodeField;
        
        private string freqFlyerCarrierField;
        
        private string freqFlyerNumberField;
        
        private bool isCOStarField;
        
        private string onePassEliteStatusField;
        
        private string skyTeamEliteStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short PassengerIndex
        {
            get
            {
                return this.passengerIndexField;
            }
            set
            {
                this.passengerIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PassengerNumber
        {
            get
            {
                return this.passengerNumberField;
            }
            set
            {
                this.passengerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MiddleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PrefixName
        {
            get
            {
                return this.prefixNameField;
            }
            set
            {
                this.prefixNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SuffixName
        {
            get
            {
                return this.suffixNameField;
            }
            set
            {
                this.suffixNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public short NumberInParty
        {
            get
            {
                return this.numberInPartyField;
            }
            set
            {
                this.numberInPartyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public short BoardYear
        {
            get
            {
                return this.boardYearField;
            }
            set
            {
                this.boardYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PassClass
        {
            get
            {
                return this.passClassField;
            }
            set
            {
                this.passClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string FreqFlyerType
        {
            get
            {
                return this.freqFlyerTypeField;
            }
            set
            {
                this.freqFlyerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string FreqFlyerID
        {
            get
            {
                return this.freqFlyerIDField;
            }
            set
            {
                this.freqFlyerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string FreqFlyerCode
        {
            get
            {
                return this.freqFlyerCodeField;
            }
            set
            {
                this.freqFlyerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string FreqFlyerCarrier
        {
            get
            {
                return this.freqFlyerCarrierField;
            }
            set
            {
                this.freqFlyerCarrierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string FreqFlyerNumber
        {
            get
            {
                return this.freqFlyerNumberField;
            }
            set
            {
                this.freqFlyerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool IsCOStar
        {
            get
            {
                return this.isCOStarField;
            }
            set
            {
                this.isCOStarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string OnePassEliteStatus
        {
            get
            {
                return this.onePassEliteStatusField;
            }
            set
            {
                this.onePassEliteStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string SkyTeamEliteStatus
        {
            get
            {
                return this.skyTeamEliteStatusField;
            }
            set
            {
                this.skyTeamEliteStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Webservices.Continental.Com/COWSPNR")]
    public partial class COWSException
    {
        
        private string codeField;
        
        private string sourceField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Webservices.Continental.Com/COWSPNR")]
    public partial class EMail
    {
        
        private short eMailNumberField;
        
        private string eMailAddressField;
        
        private SourceType sourceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short EMailNumber
        {
            get
            {
                return this.eMailNumberField;
            }
            set
            {
                this.eMailNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EMailAddress
        {
            get
            {
                return this.eMailAddressField;
            }
            set
            {
                this.eMailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SourceType SourceType
        {
            get
            {
                return this.sourceTypeField;
            }
            set
            {
                this.sourceTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Webservices.Continental.Com/COWSPNR")]
    public enum SourceType
    {
        
        /// <remarks/>
        STANDARD,
        
        /// <remarks/>
        EUA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Webservices.Continental.Com/COWSPNR")]
    public partial class StopOver
    {
        
        private string airportCodeField;
        
        private bool isDestinationField;
        
        private double stopOverInHoursField;
        
        private double stopOverInDaysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AirportCode
        {
            get
            {
                return this.airportCodeField;
            }
            set
            {
                this.airportCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsDestination
        {
            get
            {
                return this.isDestinationField;
            }
            set
            {
                this.isDestinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double StopOverInHours
        {
            get
            {
                return this.stopOverInHoursField;
            }
            set
            {
                this.stopOverInHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double StopOverInDays
        {
            get
            {
                return this.stopOverInDaysField;
            }
            set
            {
                this.stopOverInDaysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Webservices.Continental.Com/COWSPNR")]
    public partial class Ticket
    {
        
        private short passengerIndexField;
        
        private string tKTNumField;
        
        private string tKTSeqNumField;
        
        private string cpnNumField;
        
        private bool isUsedField;
        
        private bool isNoShowedField;
        
        private bool isExchangedField;
        
        private bool isRefundedField;
        
        private bool isPrintedField;
        
        private bool isPaxCheckedInField;
        
        private bool isATOControlledField;
        
        private bool isReceiptPrintedField;
        
        private bool isBrdLiftedField;
        
        private bool isUnavailableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short PassengerIndex
        {
            get
            {
                return this.passengerIndexField;
            }
            set
            {
                this.passengerIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TKTNum
        {
            get
            {
                return this.tKTNumField;
            }
            set
            {
                this.tKTNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TKTSeqNum
        {
            get
            {
                return this.tKTSeqNumField;
            }
            set
            {
                this.tKTSeqNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CpnNum
        {
            get
            {
                return this.cpnNumField;
            }
            set
            {
                this.cpnNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsUsed
        {
            get
            {
                return this.isUsedField;
            }
            set
            {
                this.isUsedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsNoShowed
        {
            get
            {
                return this.isNoShowedField;
            }
            set
            {
                this.isNoShowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool IsExchanged
        {
            get
            {
                return this.isExchangedField;
            }
            set
            {
                this.isExchangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsRefunded
        {
            get
            {
                return this.isRefundedField;
            }
            set
            {
                this.isRefundedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool IsPrinted
        {
            get
            {
                return this.isPrintedField;
            }
            set
            {
                this.isPrintedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsPaxCheckedIn
        {
            get
            {
                return this.isPaxCheckedInField;
            }
            set
            {
                this.isPaxCheckedInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool IsATOControlled
        {
            get
            {
                return this.isATOControlledField;
            }
            set
            {
                this.isATOControlledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IsReceiptPrinted
        {
            get
            {
                return this.isReceiptPrintedField;
            }
            set
            {
                this.isReceiptPrintedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool IsBrdLifted
        {
            get
            {
                return this.isBrdLiftedField;
            }
            set
            {
                this.isBrdLiftedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool IsUnavailable
        {
            get
            {
                return this.isUnavailableField;
            }
            set
            {
                this.isUnavailableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Webservices.Continental.Com/COWSPNR")]
    public partial class Segment
    {
        
        private short segmentIndexField;
        
        private string segmentTypeField;
        
        private bool isActiveSegmentField;
        
        private bool isARNKSegmentField;
        
        private string actionCodeField;
        
        private string carrierCodeField;
        
        private string bookedByField;
        
        private string operatedByField;
        
        private int flightNumberField;
        
        private int redepFlightNumberField;
        
        private string equipmentField;
        
        private string equipmentDescField;
        
        private string departureAirportField;
        
        private string departureGateField;
        
        private System.DateTime departureDateTimeField;
        
        private string arrivalAirportField;
        
        private string arrivalGateField;
        
        private System.DateTime arrivalDateTimeField;
        
        private short numPassengersField;
        
        private Ticket[] ticketsField;
        
        private string serviceClassField;
        
        private string advanceSeatsField;
        
        private string firstClassMealField;
        
        private string coachClassMealField;
        
        private string mealsField;
        
        private bool isGroupField;
        
        private string auxilliaryTextField;
        
        private bool isCodeShareField;
        
        private bool isReverseCodeShareField;
        
        private bool isPositiveSpaceRiderField;
        
        private bool isFirstSegmentField;
        
        private bool isOutBoundConnectionField;
        
        private bool isInBoundConnectionField;
        
        private bool isMarriedSegmentField;
        
        private bool isODSegmentField;
        
        private string cabinDescField;
        
        private string cabinClassField;
        
        private bool hasPremiumClassField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short SegmentIndex
        {
            get
            {
                return this.segmentIndexField;
            }
            set
            {
                this.segmentIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SegmentType
        {
            get
            {
                return this.segmentTypeField;
            }
            set
            {
                this.segmentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsActiveSegment
        {
            get
            {
                return this.isActiveSegmentField;
            }
            set
            {
                this.isActiveSegmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsARNKSegment
        {
            get
            {
                return this.isARNKSegmentField;
            }
            set
            {
                this.isARNKSegmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ActionCode
        {
            get
            {
                return this.actionCodeField;
            }
            set
            {
                this.actionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CarrierCode
        {
            get
            {
                return this.carrierCodeField;
            }
            set
            {
                this.carrierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BookedBy
        {
            get
            {
                return this.bookedByField;
            }
            set
            {
                this.bookedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OperatedBy
        {
            get
            {
                return this.operatedByField;
            }
            set
            {
                this.operatedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int FlightNumber
        {
            get
            {
                return this.flightNumberField;
            }
            set
            {
                this.flightNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int RedepFlightNumber
        {
            get
            {
                return this.redepFlightNumberField;
            }
            set
            {
                this.redepFlightNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Equipment
        {
            get
            {
                return this.equipmentField;
            }
            set
            {
                this.equipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string EquipmentDesc
        {
            get
            {
                return this.equipmentDescField;
            }
            set
            {
                this.equipmentDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DepartureAirport
        {
            get
            {
                return this.departureAirportField;
            }
            set
            {
                this.departureAirportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DepartureGate
        {
            get
            {
                return this.departureGateField;
            }
            set
            {
                this.departureGateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime DepartureDateTime
        {
            get
            {
                return this.departureDateTimeField;
            }
            set
            {
                this.departureDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ArrivalAirport
        {
            get
            {
                return this.arrivalAirportField;
            }
            set
            {
                this.arrivalAirportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ArrivalGate
        {
            get
            {
                return this.arrivalGateField;
            }
            set
            {
                this.arrivalGateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public System.DateTime ArrivalDateTime
        {
            get
            {
                return this.arrivalDateTimeField;
            }
            set
            {
                this.arrivalDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public short NumPassengers
        {
            get
            {
                return this.numPassengersField;
            }
            set
            {
                this.numPassengersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=19)]
        public Ticket[] Tickets
        {
            get
            {
                return this.ticketsField;
            }
            set
            {
                this.ticketsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ServiceClass
        {
            get
            {
                return this.serviceClassField;
            }
            set
            {
                this.serviceClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string AdvanceSeats
        {
            get
            {
                return this.advanceSeatsField;
            }
            set
            {
                this.advanceSeatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string FirstClassMeal
        {
            get
            {
                return this.firstClassMealField;
            }
            set
            {
                this.firstClassMealField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string CoachClassMeal
        {
            get
            {
                return this.coachClassMealField;
            }
            set
            {
                this.coachClassMealField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Meals
        {
            get
            {
                return this.mealsField;
            }
            set
            {
                this.mealsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public bool IsGroup
        {
            get
            {
                return this.isGroupField;
            }
            set
            {
                this.isGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string AuxilliaryText
        {
            get
            {
                return this.auxilliaryTextField;
            }
            set
            {
                this.auxilliaryTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public bool IsCodeShare
        {
            get
            {
                return this.isCodeShareField;
            }
            set
            {
                this.isCodeShareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public bool IsReverseCodeShare
        {
            get
            {
                return this.isReverseCodeShareField;
            }
            set
            {
                this.isReverseCodeShareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public bool IsPositiveSpaceRider
        {
            get
            {
                return this.isPositiveSpaceRiderField;
            }
            set
            {
                this.isPositiveSpaceRiderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public bool IsFirstSegment
        {
            get
            {
                return this.isFirstSegmentField;
            }
            set
            {
                this.isFirstSegmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public bool IsOutBoundConnection
        {
            get
            {
                return this.isOutBoundConnectionField;
            }
            set
            {
                this.isOutBoundConnectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public bool IsInBoundConnection
        {
            get
            {
                return this.isInBoundConnectionField;
            }
            set
            {
                this.isInBoundConnectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public bool IsMarriedSegment
        {
            get
            {
                return this.isMarriedSegmentField;
            }
            set
            {
                this.isMarriedSegmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public bool IsODSegment
        {
            get
            {
                return this.isODSegmentField;
            }
            set
            {
                this.isODSegmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string CabinDesc
        {
            get
            {
                return this.cabinDescField;
            }
            set
            {
                this.cabinDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string CabinClass
        {
            get
            {
                return this.cabinClassField;
            }
            set
            {
                this.cabinClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public bool HasPremiumClass
        {
            get
            {
                return this.hasPremiumClassField;
            }
            set
            {
                this.hasPremiumClassField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface PNRServiceSoapChannel : UAWSPNRServiceERes.PNRServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class PNRServiceSoapClient : System.ServiceModel.ClientBase<UAWSPNRServiceERes.PNRServiceSoap>, UAWSPNRServiceERes.PNRServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PNRServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PNRServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), PNRServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PNRServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PNRServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PNRServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PNRServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PNRServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> HeartBeatAsync()
        {
            return base.Channel.HeartBeatAsync();
        }
        
        public System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordsByEmployeeIDAsync(string employeeID, string activePNROnly, string accessCode)
        {
            return base.Channel.GetPNRRecordsByEmployeeIDAsync(employeeID, activePNROnly, accessCode);
        }
        
        public System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetReservationByEmployeeIDAsync(string employeeID, string activePNROnly, string accessCode)
        {
            return base.Channel.GetReservationByEmployeeIDAsync(employeeID, activePNROnly, accessCode);
        }
        
        public System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetReservationByOnePassAsync(string onePass, string activePNROnly, string accessCode)
        {
            return base.Channel.GetReservationByOnePassAsync(onePass, activePNROnly, accessCode);
        }
        
        public System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordsByOnePassAsync(string onePass, string activePNROnly, string accessCode)
        {
            return base.Channel.GetPNRRecordsByOnePassAsync(onePass, activePNROnly, accessCode);
        }
        
        public System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordByPNRAsync(string recordLocator, string accessCode)
        {
            return base.Channel.GetPNRRecordByPNRAsync(recordLocator, accessCode);
        }
        
        public System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordByPNRForClubAsync(string recordLocator, string accessCode)
        {
            return base.Channel.GetPNRRecordByPNRForClubAsync(recordLocator, accessCode);
        }
        
        public System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordByRecordLocatorAsync(string recordLocator, string redeploy, string accessCode)
        {
            return base.Channel.GetPNRRecordByRecordLocatorAsync(recordLocator, redeploy, accessCode);
        }
        
        public System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordByPNRNoItineraryValidationAsync(string recordLocator, string accessCode)
        {
            return base.Channel.GetPNRRecordByPNRNoItineraryValidationAsync(recordLocator, accessCode);
        }
        
        public System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordByPNRWithTktDetailAsync(string recordLocator, string accessCode)
        {
            return base.Channel.GetPNRRecordByPNRWithTktDetailAsync(recordLocator, accessCode);
        }
        
        public System.Threading.Tasks.Task<UAWSPNRServiceERes.COWSReturnType> GetPNRRecordByRecordLocatorWithTktDetailAsync(string recordLocator, string redeploy, string accessCode)
        {
            return base.Channel.GetPNRRecordByRecordLocatorWithTktDetailAsync(recordLocator, redeploy, accessCode);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PNRServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PNRServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PNRServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://wspnrpss.nam.coair.com:9910/COWSPNRService/PNRService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PNRServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://wspnrpss.nam.coair.com:9910/COWSPNRService/PNRService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PNRServiceSoap,
            
            PNRServiceSoap12,
        }
    }
}
