#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM artifactorycloud.ual.com/l-docker-releases/datadog/dotnet/aspnet:6.0.5-2.10.0 AS base

WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM artifactorycloud.ual.com/l-docker/ms/dotnet/core/sdk:6.0 AS build
WORKDIR /

COPY ["src/Services/Shopping/TripPlannerService/United.Mobile.Services.TripPlannerService.Api/United.Mobile.Services.TripPlannerService.Api.csproj", "src/Services/Shopping/TripPlannerService/United.Mobile.Services.TripPlannerService.Api/"]

ARG NUGET_PASSWORD
ARG NUGET_USERNAME


RUN dotnet nuget add source https://artifactorycloud.ual.com/artifactory/api/nuget/v3/v-nuget \
            -n artifactory \
            -u ${NUGET_USERNAME}  \
            -p ${NUGET_PASSWORD} \
            --store-password-in-clear-text


COPY . .
WORKDIR "/src/Services/Shopping/TripPlannerService/United.Mobile.Services.TripPlannerService.Api"

FROM build AS publish
ARG VERSION
RUN dotnet publish "United.Mobile.Services.TripPlannerService.Api.csproj" -c Debug -r linux-x64
RUN mkdir VC/
RUN cp -f -r bin/Debug/net6.0/linux-x64/* VC
RUN pwsh -Command Invoke-Command -ScriptBlock "{Compress-Archive -Path "VC/*" -DestinationPath "VC/${VERSION}.zip"}"

FROM artifactorycloud.ual.com/v-docker/btw/harness/images/veracode-powershell-java-alpine:latest AS release
ARG VERSION
ARG VERACODE_ID
ARG VERACODE_KEY
ARG APPNAME
ARG PURPOSE
COPY --from=publish /src/Services/Shopping/TripPlannerService/United.Mobile.Services.TripPlannerService.Api/VC/${VERSION}.zip . 
COPY --from=build /devops-utilities/veracode-execute.ps1 .  
RUN /opt/microsoft/powershell/7/pwsh ./veracode-execute.ps1 ${VERACODE_ID} ${VERACODE_KEY} ${APPNAME} ${VERSION} ${VERSION}.zip ${PURPOSE}