#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM artifactorycloud.ual.com/l-docker-releases/datadog/dotnet/aspnet:6.0.5-2.10.0 AS base

WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM artifactorycloud.ual.com/l-docker/ms/dotnet/core/sdk:6.0 AS build
WORKDIR /
COPY ["src/Services/Shopping/TripPlannerService/United.Mobile.Services.TripPlannerService.Api/United.Mobile.Services.TripPlannerService.Api.csproj", "src/Services/Shopping/TripPlannerService/United.Mobile.Services.TripPlannerService.Api/"]
COPY ["src/Core/United.Utility/United.Utility.csproj", "src/Core/United.Utility/"]
COPY ["src/Core/United.Ebs.Logging/United.Ebs.Logging.csproj", "src/Core/United.Ebs.Logging/"]
COPY ["src/Model/United.Mobile.Model.Common/United.Mobile.Model.Common.csproj", "src/Model/United.Mobile.Model.Common/"]
COPY ["src/Model/SeatEngine/United.Mobile.Model.SeatEngine/United.Mobile.Model.SeatEngine.csproj", "src/Model/SeatEngine/United.Mobile.Model.SeatEngine/"]
COPY ["src/Model.Internal/United.Mobile.Model.Internal.Exception/United.Mobile.Model.Internal.Exception.csproj", "src/Model.Internal/United.Mobile.Model.Internal.Exception/"]
COPY ["src/Services/Shopping/TripPlannerService/United.Mobile.Services.TripPlannerService.Domain/United.Mobile.Services.TripPlannerService.Domain.csproj", "src/Services/Shopping/TripPlannerService/United.Mobile.Services.TripPlannerService.Domain/"]
COPY ["src/DataAccess/United.Mobile.DataAccess.Common/United.Mobile.DataAccess.Common.csproj", "src/DataAccess/United.Mobile.DataAccess.Common/"]
COPY ["src/Model.Internal/United.Definition/United.Mobile.Model.Internal.Common.csproj", "src/Model.Internal/United.Definition/"]
COPY ["src/Model.Internal/United.Mobile.Model.Internal/United.Mobile.Model.Internal.csproj", "src/Model.Internal/United.Mobile.Model.Internal/"]
COPY ["src/Model/eRes/United.Mobile.Model.HomePageContent/United.Mobile.Model.HomePageContent.csproj", "src/Model/eRes/United.Mobile.Model.HomePageContent/"]
COPY ["src/DataAccess/Shopping/United.Mobile.DataAccess.TripPlannerService/United.Mobile.DataAccess.TripPlannerService/United.Mobile.DataAccess.TripPlannerService.csproj", "src/DataAccess/Shopping/United.Mobile.DataAccess.TripPlannerService/United.Mobile.DataAccess.TripPlannerService/"]
COPY ["src/Model/Shopping/United.Mobile.Model.TripPlannerGetService/United.Mobile.Model.TripPlannerGetService.csproj", "src/Model/Shopping/United.Mobile.Model.TripPlannerGetService/"]
COPY ["src/Model/Shopping/United.Mobile.Model.Common/United.Mobile.Model.Shopping.Common.csproj", "src/Model/Shopping/United.Mobile.Model.Common/"]
COPY ["src/Model/Ancillary/United.Mobile.Model.Catalog/United.Mobile.Model.Catalog.csproj", "src/Model/Ancillary/United.Mobile.Model.Catalog/"]
COPY ["src/Model/PNRManagement/United.Mobile.Model.PNRManagement/United.Mobile.Model.PNRManagement.csproj", "src/Model/PNRManagement/United.Mobile.Model.PNRManagement/"]
COPY ["src/Model/Shopping/United.Mobile.Model.TripPlannerService/United.Mobile.Model.TripPlannerService.csproj", "src/Model/Shopping/United.Mobile.Model.TripPlannerService/"]
COPY ["src/Core/United.Utility.Middleware/United.Utility.Middleware.csproj", "src/Core/United.Utility.Middleware/"]

ARG Username
ARG PAT
RUN echo '<?xml version="1.0" encoding="utf-8"?> \
<configuration> \
  <packageSources> \
    <clear /> \
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" /> \
    <add key="ArtifactoryNuGetV3" value="https://artifactory.ual.com/artifactory/api/nuget/v3/nuget" protocolVersion="3" /> \
    <add key="EresNuget" value="http://vcld36gdersas01.global.ual.com/EresNuget/nuget" /> \
  </packageSources> \
  <activePackageSource> \
    <add key="All" value="(Aggregate source)" /> \
  </activePackageSource> \
</configuration>' > nuget.config && \
if [ -n "$Username" ] && [ -n "$PAT" ]; then \
sed -i "s|</configuration>|<packageSourceCredentials><Products><add key=\"Username\" value=\"PAT\" /><add key=\"ClearTextPassword\" value=\"${PAT}\" /></Products><DemoFeed><add key=\"Username\" value=\"${Username}\" /><add key=\"ClearTextPassword\" value=\"${PAT}\" /></DemoFeed></packageSourceCredentials></configuration>|" nuget.config; \
fi && \
cat ./nuget.config

COPY . .
WORKDIR "/src/Services/Shopping/TripPlannerService/United.Mobile.Services.TripPlannerService.Api"

FROM build AS publish
RUN dotnet publish "United.Mobile.Services.TripPlannerService.Api.csproj" -c Release --self-contained -r linux-x64 -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "United.Mobile.Services.TripPlannerService.Api.dll"]